# Generated by Django 3.2.14 on 2022-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[(0, 'Pasta'), (1, 'Salads')], max_length=90),
        ),
    ]
