# Generated by Django 3.2.14 on 2024-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shortDescrition',
            field=models.TextField(blank=True),
        ),
    ]
