# Generated by Django 3.2.14 on 2024-04-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_recipe_shortdescrition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='shortDescrition',
            new_name='shortDescription',
        ),
    ]
